[2024-12-07T19:26:29.628+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T19:26:29.642+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medal_count_dag.calc_bronze_task manual__2024-12-07T19:21:19.144510+00:00 [queued]>
[2024-12-07T19:26:29.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medal_count_dag.calc_bronze_task manual__2024-12-07T19:21:19.144510+00:00 [queued]>
[2024-12-07T19:26:29.650+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-07T19:26:29.662+0000] {taskinstance.py:2889} INFO - Executing <Task(MySqlOperator): calc_bronze_task> on 2024-12-07 19:21:19.144510+00:00
[2024-12-07T19:26:29.668+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4660) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T19:26:29.670+0000] {standard_task_runner.py:72} INFO - Started process 4662 to run task
[2024-12-07T19:26:29.670+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medal_count_dag', 'calc_bronze_task', 'manual__2024-12-07T19:21:19.144510+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpi0nvnrqb']
[2024-12-07T19:26:29.671+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask calc_bronze_task
[2024-12-07T19:26:29.708+0000] {task_command.py:467} INFO - Running <TaskInstance: medal_count_dag.calc_bronze_task manual__2024-12-07T19:21:19.144510+00:00 [running]> on host a693d8a2436c
[2024-12-07T19:26:29.910+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medal_count_dag' AIRFLOW_CTX_TASK_ID='calc_bronze_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T19:21:19.144510+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T19:21:19.144510+00:00'
[2024-12-07T19:26:29.911+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T19:26:29.912+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T19:26:29.913+0000] {logging_mixin.py:190} INFO - Current task name:calc_bronze_task state:running start_date:2024-12-07 19:26:29.643092+00:00
[2024-12-07T19:26:29.914+0000] {logging_mixin.py:190} INFO - Dag name:medal_count_dag and current dag run status:running
[2024-12-07T19:26:29.915+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T19:26:29.915+0000] {sql.py:278} INFO - Executing: 
INSERT INTO medal_count (medal_type, count, created_at)
VALUES ('Bronze', (SELECT COUNT(*) FROM olympic_dataset.athlete_event_results WHERE medal = 'Bronze'), NOW());
[2024-12-07T19:26:29.922+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:26:29.928+0000] {base.py:84} INFO - Retrieving connection 'goit_mysql_db_volodymyrdubrovskyi'
[2024-12-07T19:26:30.146+0000] {sql.py:544} INFO - Running statement: 
INSERT INTO medal_count (medal_type, count, created_at)
VALUES ('Bronze', (SELECT COUNT(*) FROM olympic_dataset.athlete_event_results WHERE medal = 'Bronze'), NOW());, parameters: None
[2024-12-07T19:26:30.192+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'neo_data.medal_count' doesn't exist")
[2024-12-07T19:26:30.202+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-07T19:26:30.203+0000] {logging_mixin.py:190} INFO - Task start:2024-12-07 19:26:29.643092+00:00 end:2024-12-07 19:26:30.202139+00:00 duration:0.559047
[2024-12-07T19:26:30.204+0000] {logging_mixin.py:190} INFO - Task:<Task(MySqlOperator): calc_bronze_task> dag:<DAG: medal_count_dag> dagrun:<DagRun medal_count_dag @ 2024-12-07 19:21:19.144510+00:00: manual__2024-12-07T19:21:19.144510+00:00, state:running, queued_at: 2024-12-07 19:21:19.151907+00:00. externally triggered: True>
[2024-12-07T19:26:30.205+0000] {logging_mixin.py:190} INFO - Failure caused by (1146, "Table 'neo_data.medal_count' doesn't exist")
[2024-12-07T19:26:30.205+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=medal_count_dag, task_id=calc_bronze_task, run_id=manual__2024-12-07T19:21:19.144510+00:00, execution_date=20241207T192119, start_date=20241207T192629, end_date=20241207T192630
[2024-12-07T19:26:30.214+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T19:26:30.214+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task calc_bronze_task ((1146, "Table 'neo_data.medal_count' doesn't exist"); 4662)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'neo_data.medal_count' doesn't exist")
[2024-12-07T19:26:30.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T19:26:30.262+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T19:26:30.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
